[package]
name = "rpi-fan-control-rs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rpi_fan_control"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rppal = "^0.14.0"
once_cell = "^1.16.0"